#!/usr/bin/env bash

~/Dropbox/projects/rrdtool/scripts/./temperature
~/Dropbox/projects/rrdtool/scripts/./network-usage

cd ~/.log
convert temperature-day.png network-usage-day.png -append background.png
